### PR TITLE
fix: data is not displayed when modifying the image.

### LINKED ISSUE #12: 编辑分组数据不回显，编辑图片也一样
### 问题描述
编辑分组没有回显数据
image，
还有编辑图片，第一次点编辑，有回显数据，第二次点编辑就没有回显数据了

### PR DESCRIPTION
**Pull request by LIlGG**
#### What type of PR is this?

/kind bug

#### Which issue(s) this PR fixes:

Fixes #12 

#### Special notes for your reviewer:

1. 点击一个需要修改的图片
2. 关闭弹出的修改框
3. 再次点击此图片，查看是否成功回显待修改的数据

#### Does this PR introduce a user-facing change?
```release-note
解决第二次点击编辑图片时不回显数据的问题
```

### CODE REVIEW

**Review by guqing — COMMENTED** [review]
/approve

**Review by ruibaby — APPROVED** [review]
/lgtm

**Pull request merged**
